package cli

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/charmbracelet/x/term"
	"github.com/spf13/cobra"

	"github.com/scolastico-dev/one-man-office/internal/config"
	"github.com/scolastico-dev/one-man-office/internal/globalhome"
	"github.com/scolastico-dev/one-man-office/internal/office"
	"github.com/scolastico-dev/one-man-office/internal/pluginmanager"
	"github.com/scolastico-dev/one-man-office/internal/selfupdate"
)

var (
	latestRelease = func(ctx context.Context) (selfupdate.Release, error) {
		return (selfupdate.Client{}).Latest(ctx)
	}
	installRelease = func(ctx context.Context, release selfupdate.Release, target string) error {
		return (selfupdate.Client{}).Install(ctx, release, target)
	}
	currentExecutable   = os.Executable
	launchRestart       = restartProcess
	inputIsTerminal     = isTerminal
	templateUpdatePlan  = office.PlanTemplateUpdate
	templateUpdate      = office.UpdateTemplatesWithPreview
	pluginSyncAll       = pluginmanager.SyncAllWithPreview
	globalPluginSyncAll = pluginmanager.SyncAllAtWithPreview
)

func runStartupChecks(cmd *cobra.Command, dir string, cfg *config.Config, version string, allowPrompt bool) (bool, error) {
	interactive := allowPrompt && inputIsTerminal(cmd.InOrStdin())
	input := bufio.NewReader(cmd.InOrStdin())
	if cfg.Startup.CheckSelfUpdate && version != "dev" && version != "test" && version != "" {
		ctx, cancel := startupContext(time.Duration(cfg.Startup.CheckTimeout))
		release, err := latestRelease(ctx)
		cancel()
		if err != nil {
			fmt.Fprintln(cmd.ErrOrStderr(), "WARNING: could not check for omo updates:", err)
		} else if selfupdate.IsNewer(version, release.Tag) {
			fmt.Fprintf(cmd.ErrOrStderr(), "omo %s is available (running %s).\n", release.Tag, version)
			if interactive && askYesNo(input, cmd.OutOrStdout(), "Update omo and restart now?") {
				target, err := currentExecutable()
				if err != nil {
					return false, err
				}
				if resolved, err := filepath.EvalSymlinks(target); err == nil {
					target = resolved
				}
				ctx, cancel := startupContext(time.Duration(cfg.Startup.CheckTimeout) * 12)
				err = installRelease(ctx, release, target)
				cancel()
				if err != nil {
					return false, fmt.Errorf("self-update: %w", err)
				}
				fmt.Fprintf(cmd.OutOrStdout(), "updated omo to %s; restarting\n", release.Tag)
				if err := launchRestart(target); err != nil {
					return false, fmt.Errorf("restart updated omo: %w", err)
				}
				return true, nil
			}
		}
	}
	if cfg.Startup.CheckTemplates {
		outdated, err := office.TemplatesOutdated(dir)
		if err != nil {
			fmt.Fprintln(cmd.ErrOrStderr(), "WARNING: could not check embedded assets:", err)
		} else if outdated {
			fmt.Fprintln(cmd.ErrOrStderr(), ".omo/messages, .omo/prompts, or bundled plugins were generated by an older omo version.")
			plan, planErr := templateUpdatePlan(dir)
			if planErr != nil {
				fmt.Fprintln(cmd.ErrOrStderr(), "WARNING: could not preview embedded asset update:", planErr)
			} else {
				for _, path := range plan {
					fmt.Fprintln(cmd.OutOrStdout(), "update would change", path)
				}
				if interactive && askYesNo(input, cmd.OutOrStdout(), "Run 'omo setup --update' and restart now? (This replaces template and bundled-plugin edits.)") {
					if _, err := templateUpdate(dir, func(path string) {
						fmt.Fprintln(cmd.OutOrStdout(), "will update", path)
					}); err != nil {
						return false, fmt.Errorf("update templates: %w", err)
					}
					if cfg.GitIntegration && !gitPathIgnored(dir, filepath.Join(".omo", "omo.yaml")) && askYesNo(input, cmd.OutOrStdout(), "Commit the updated .omo files on the current branch?") {
						if err := commitTemplateUpdate(dir, plan); err != nil {
							return false, fmt.Errorf("commit template update: %w", err)
						}
						fmt.Fprintln(cmd.OutOrStdout(), "committed explicit updated .omo files")
					}
					target, err := currentExecutable()
					if err != nil {
						return false, err
					}
					fmt.Fprintln(cmd.OutOrStdout(), "updated embedded templates and plugins; restarting")
					if err := launchRestart(target); err != nil {
						return false, fmt.Errorf("restart after template update: %w", err)
					}
					return true, nil
				}
			}
		}
	}
	if cfg.Plugins.UpdateOnStart && len(cfg.Plugins.Installed) > 0 {
		timeout := time.Duration(cfg.Startup.CheckTimeout) * 12
		ctx, cancel := startupContext(timeout)
		results, errs := pluginSyncAll(ctx, dir, cfg.Plugins, func(plan pluginmanager.Result) {
			printPluginPlan(cmd.ErrOrStderr(), "plugin", plan)
		})
		cancel()
		for _, result := range results {
			if result.Changed {
				fmt.Fprintf(cmd.ErrOrStderr(), "updated plugin %s to %s\n", result.Name, shortRevision(result.Revision))
			}
		}
		for _, err := range errs {
			fmt.Fprintln(cmd.ErrOrStderr(), "WARNING: could not update plugin:", err)
		}
	}
	home, err := globalhome.Open()
	if err != nil {
		return false, err
	}
	if home.Config.Plugins.UpdateOnStart && len(home.Config.Plugins.Installed) > 0 {
		ctx, cancel := startupContext(time.Duration(cfg.Startup.CheckTimeout) * 12)
		results, errs := globalPluginSyncAll(ctx, filepath.Join(home.Dir, "plugins"), filepath.Join(home.Dir, "config.yaml"), home.Config.Plugins, func(plan pluginmanager.Result) {
			printPluginPlan(cmd.ErrOrStderr(), "global plugin", plan)
		})
		cancel()
		for _, result := range results {
			if result.Changed {
				fmt.Fprintf(cmd.ErrOrStderr(), "updated global plugin %s to %s\n", result.Name, shortRevision(result.Revision))
			}
		}
		for _, err := range errs {
			fmt.Fprintln(cmd.ErrOrStderr(), "WARNING: could not update global plugin:", err)
		}
	}
	return false, nil
}

func gitPathIgnored(dir, path string) bool {
	cmd := exec.Command("git", "-C", dir, "check-ignore", "-q", "--", path)
	return cmd.Run() == nil
}

func commitTemplateUpdate(dir string, paths []string) error {
	files := make([]string, 0, len(paths))
	for _, path := range paths {
		if strings.HasSuffix(path, "/") {
			continue
		}
		files = append(files, path)
	}
	if len(files) == 0 {
		return nil
	}
	addArgs := append([]string{"-C", dir, "add", "--"}, files...)
	if out, err := exec.Command("git", addArgs...).CombinedOutput(); err != nil {
		return fmt.Errorf("git add: %w: %s", err, strings.TrimSpace(string(out)))
	}
	commitArgs := append([]string{"-C", dir, "commit", "-m", "omo: update embedded templates", "--"}, files...)
	if out, err := exec.Command("git", commitArgs...).CombinedOutput(); err != nil {
		return fmt.Errorf("git commit: %w: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

func printPluginPlan(out io.Writer, label string, plan pluginmanager.Result) {
	if plan.Previous == "" {
		fmt.Fprintf(out, "will install %s %s at %s\n", label, plan.Name, shortRevision(plan.Revision))
	} else {
		fmt.Fprintf(out, "will update %s %s from %s to %s\n", label, plan.Name, shortRevision(plan.Previous), shortRevision(plan.Revision))
	}
}

func startupContext(timeout time.Duration) (context.Context, context.CancelFunc) {
	if timeout <= 0 {
		return context.WithCancel(context.Background())
	}
	return context.WithTimeout(context.Background(), timeout)
}

func isTerminal(r io.Reader) bool {
	f, ok := r.(*os.File)
	if !ok {
		return false
	}
	return term.IsTerminal(f.Fd())
}

func askYesNo(in *bufio.Reader, out io.Writer, question string) bool {
	fmt.Fprintf(out, "%s [y/N] ", question)
	line, err := in.ReadString('\n')
	if err != nil && len(line) == 0 {
		return false
	}
	switch strings.ToLower(strings.TrimSpace(line)) {
	case "y", "yes":
		return true
	default:
		return false
	}
}
