package cli

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/scolastico-dev/one-man-office/internal/config"
	"github.com/scolastico-dev/one-man-office/internal/office"
	"github.com/scolastico-dev/one-man-office/internal/pluginmanager"
	"github.com/scolastico-dev/one-man-office/internal/selfupdate"
)

var (
	latestRelease = func(ctx context.Context) (selfupdate.Release, error) {
		return (selfupdate.Client{}).Latest(ctx)
	}
	installRelease = func(ctx context.Context, release selfupdate.Release, target string) error {
		return (selfupdate.Client{}).Install(ctx, release, target)
	}
	currentExecutable = os.Executable
	launchRestart     = restartProcess
	inputIsTerminal   = isTerminal
	pluginSyncAll     = pluginmanager.SyncAll
)

func runStartupChecks(cmd *cobra.Command, dir string, cfg *config.Config, version string, allowPrompt bool) (bool, error) {
	interactive := allowPrompt && inputIsTerminal(cmd.InOrStdin())
	input := bufio.NewReader(cmd.InOrStdin())
	if cfg.Startup.CheckSelfUpdate && version != "dev" && version != "test" && version != "" {
		ctx, cancel := startupContext(time.Duration(cfg.Startup.CheckTimeout))
		release, err := latestRelease(ctx)
		cancel()
		if err != nil {
			fmt.Fprintln(cmd.ErrOrStderr(), "WARNING: could not check for omo updates:", err)
		} else if selfupdate.IsNewer(version, release.Tag) {
			fmt.Fprintf(cmd.ErrOrStderr(), "omo %s is available (running %s).\n", release.Tag, version)
			if interactive && askYesNo(input, cmd.OutOrStdout(), "Update omo and restart now?") {
				target, err := currentExecutable()
				if err != nil {
					return false, err
				}
				if resolved, err := filepath.EvalSymlinks(target); err == nil {
					target = resolved
				}
				ctx, cancel := startupContext(time.Duration(cfg.Startup.CheckTimeout) * 12)
				err = installRelease(ctx, release, target)
				cancel()
				if err != nil {
					return false, fmt.Errorf("self-update: %w", err)
				}
				fmt.Fprintf(cmd.OutOrStdout(), "updated omo to %s; restarting\n", release.Tag)
				if err := launchRestart(target); err != nil {
					return false, fmt.Errorf("restart updated omo: %w", err)
				}
				return true, nil
			}
		}
	}
	if cfg.Startup.CheckTemplates {
		outdated, err := office.TemplatesOutdated(dir)
		if err != nil {
			fmt.Fprintln(cmd.ErrOrStderr(), "WARNING: could not check embedded assets:", err)
		} else if outdated {
			fmt.Fprintln(cmd.ErrOrStderr(), ".omo/messages, .omo/prompts, or bundled plugins were generated by an older omo version.")
			if interactive && askYesNo(input, cmd.OutOrStdout(), "Run 'omo setup --update' and restart now? (This replaces template and bundled-plugin edits.)") {
				if _, err := office.UpdateTemplates(dir); err != nil {
					return false, fmt.Errorf("update templates: %w", err)
				}
				target, err := currentExecutable()
				if err != nil {
					return false, err
				}
				fmt.Fprintln(cmd.OutOrStdout(), "updated embedded templates and plugins; restarting")
				if err := launchRestart(target); err != nil {
					return false, fmt.Errorf("restart after template update: %w", err)
				}
				return true, nil
			}
		}
	}
	if cfg.Plugins.UpdateOnStart && len(cfg.Plugins.Installed) > 0 {
		timeout := time.Duration(cfg.Startup.CheckTimeout) * 12
		ctx, cancel := startupContext(timeout)
		results, errs := pluginSyncAll(ctx, dir, cfg.Plugins)
		cancel()
		for _, result := range results {
			if result.Changed {
				fmt.Fprintf(cmd.ErrOrStderr(), "updated plugin %s to %s\n", result.Name, shortRevision(result.Revision))
			}
		}
		for _, err := range errs {
			fmt.Fprintln(cmd.ErrOrStderr(), "WARNING: could not update plugin:", err)
		}
	}
	return false, nil
}

func startupContext(timeout time.Duration) (context.Context, context.CancelFunc) {
	if timeout <= 0 {
		return context.WithCancel(context.Background())
	}
	return context.WithTimeout(context.Background(), timeout)
}

func isTerminal(r io.Reader) bool {
	f, ok := r.(*os.File)
	if !ok {
		return false
	}
	info, err := f.Stat()
	return err == nil && info.Mode()&os.ModeCharDevice != 0
}

func askYesNo(in *bufio.Reader, out io.Writer, question string) bool {
	fmt.Fprintf(out, "%s [y/N] ", question)
	line, err := in.ReadString('\n')
	if err != nil && len(line) == 0 {
		return false
	}
	switch strings.ToLower(strings.TrimSpace(line)) {
	case "y", "yes":
		return true
	default:
		return false
	}
}
